refactor code

diff --git a/src/BaristaService/Dockerfile b/src/BaristaService/Dockerfile
--- a/src/BaristaService/Dockerfile
+++ b/src/BaristaService/Dockerfile
@@ -3,7 +3,7 @@
 FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
 WORKDIR /app
 EXPOSE 5003
-HEALTHCHECK CMD curl --fail http://localhost:5003 || exit 1
+# HEALTHCHECK CMD curl --fail http://localhost:5003 || exit 1
 
 FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
 WORKDIR /src
@@ -15,12 +15,15 @@ COPY ["src/Libs/CoffeeShop.Contracts/CoffeeShop.Contracts.csproj", "src/Libs/Cof
 RUN dotnet restore "src/BaristaService/BaristaService.csproj"
 COPY . .
 WORKDIR "/src/src/BaristaService"
-RUN dotnet build "BaristaService.csproj" -c Release -o /app/build -r linux-x64 /p:PublishReadyToRun=true
+# RUN dotnet build "BaristaService.csproj" -c Release -o /app/build -r linux-x64 /p:PublishReadyToRun=true
+RUN dotnet build "BaristaService.csproj" -c Release -o /app/build
 
 FROM build AS publish
-RUN dotnet publish "BaristaService.csproj" -c Release -o /app/publish -r linux-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true
+# RUN dotnet publish "BaristaService.csproj" -c Release -o /app/publish -r linux-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true
+RUN dotnet publish "BaristaService.csproj" -c Release -o /app/publish
 
 FROM base AS final
 WORKDIR /app
 COPY --from=publish /app/publish .
-CMD ["./BaristaService"]
+# CMD ["./BaristaService"]
+ENTRYPOINT ["dotnet", "BaristaService.dll"]
diff --git a/src/ProductService/Dockerfile b/src/ProductService/Dockerfile
--- a/src/ProductService/Dockerfile
+++ b/src/ProductService/Dockerfile
@@ -4,7 +4,7 @@ FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
 WORKDIR /app
 EXPOSE 5001
 EXPOSE 15001
-HEALTHCHECK CMD curl --fail http://localhost:5001 || exit 1
+# HEALTHCHECK CMD curl --fail http://localhost:5001 || exit 1
 
 FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
 WORKDIR /src
@@ -15,12 +15,15 @@ COPY ["src/Libs/N8T.Infrastructure/N8T.Infrastructure.csproj", "src/Libs/N8T.Inf
 RUN dotnet restore "src/ProductService/ProductService.csproj"
 COPY . .
 WORKDIR "/src/src/ProductService"
-RUN dotnet build "ProductService.csproj" -c Release -o /app/build -r linux-x64 /p:PublishReadyToRun=true
+# RUN dotnet build "ProductService.csproj" -c Release -o /app/build -r linux-x64 /p:PublishReadyToRun=true
+RUN dotnet build "ProductService.csproj" -c Release -o /app/build
 
 FROM build AS publish
-RUN dotnet publish "ProductService.csproj" -c Release -o /app/publish -r linux-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true
+# RUN dotnet publish "ProductService.csproj" -c Release -o /app/publish -r linux-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true
+RUN dotnet publish "ProductService.csproj" -c Release -o /app/publish
 
 FROM base AS final
 WORKDIR /app
 COPY --from=publish /app/publish .
-CMD ["./ProductService"]
+# CMD ["./ProductService"]
+ENTRYPOINT ["dotnet", "ProductService.dll"]
diff --git a/src/ReverseProxy/Dockerfile b/src/ReverseProxy/Dockerfile
--- a/src/ReverseProxy/Dockerfile
+++ b/src/ReverseProxy/Dockerfile
@@ -2,8 +2,8 @@
 
 FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
 WORKDIR /app
-EXPOSE 5000
-HEALTHCHECK CMD curl --fail http://localhost:5000 || exit 1
+EXPOSE 8080
+# HEALTHCHECK CMD curl --fail http://localhost:8080 || exit 1
 
 FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
 WORKDIR /src
@@ -13,12 +13,15 @@ COPY ["src/Libs/N8T.Core/N8T.Core.csproj", "src/Libs/N8T.Core/"]
 RUN dotnet restore "src/ReverseProxy/ReverseProxy.csproj"
 COPY . .
 WORKDIR "/src/src/ReverseProxy"
-RUN dotnet build "ReverseProxy.csproj" -c Release -o /app/build -r linux-x64 /p:PublishReadyToRun=true
+# RUN dotnet build "ReverseProxy.csproj" -c Release -o /app/build -r linux-x64 /p:PublishReadyToRun=true
+RUN dotnet build "ReverseProxy.csproj" -c Release -o /app/build
 
 FROM build AS publish
-RUN dotnet publish "ReverseProxy.csproj" -c Release -o /app/publish -r linux-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true
+# RUN dotnet publish "ReverseProxy.csproj" -c Release -o /app/publish -r linux-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true
+RUN dotnet publish "ReverseProxy.csproj" -c Release -o /app/publish
 
 FROM base AS final
 WORKDIR /app
 COPY --from=publish /app/publish .
-CMD ["./ReverseProxy"]
+# CMD ["./ReverseProxy"]
+ENTRYPOINT ["dotnet", "ReverseProxy.dll"]
